"""Is the listener overfitting the training vocabulary? (docs/log.md, "A
generated held-out-words test set").

`new boards` and `held-out words, generated` (train_listener_net.load_sets)
are generated by the same procedure (collect_listener_data.py: the same clue
mix, reveals and k), on boards of the training words and of the 150 held-out
words respectively. Neither was trained or selected on. So the R² gap between
them is the cost of meeting words the model never saw, and a listener whose
gap is large has learned word-specific behaviour. The held-out words were
drawn uniformly from the 400 (codenames/board.py::load_holdout_wordlist), so
no difference in difficulty is expected from the words themselves.

Reported per booster: R² pooled, at pick 1 and at picks 2+ on each set, with
a 95% bootstrap over boards for each set's pooled R², and the gap.

    python scripts/tools/compare_vocab_gap.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "pipeline"))

CACHE = Path(__file__).resolve().parents[2] / "cache"
BOOSTERS = [
    ("incumbent (deployed)", "listener_gbt.txt", None),
    ("44 features, current recipe", "listener_gbt_control44.txt", None),
    ("  + within-turn", "listener_gbt_control44.txt", "sequential_listener_control44.json"),
    ("isa", "listener_gbt_isa.txt", None),
    ("conceptnet", "listener_gbt_conceptnet.txt", None),
    ("assoc", "listener_gbt_assoc_features.txt", None),
]
SETS = ("new boards", "held-out words, generated")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.parse_args()

    import lightgbm as lgb

    from codenames.listener_net import WordVectors
    from codenames.sequential_listener import SequentialParams
    from train_joint_listener import Events
    from train_listener_net import gbt_scores, load_sets

    sets = load_sets()
    vw = WordVectors()
    ev = {s: Events(sets[s], vw) for s in SETS}
    for s in SETS:
        e = ev[s]
        print(f"{s}: {len(sets[s])} positions, {len(e.step)} events, {len(set(e.board))} boards, "
              f"mean k {np.mean([p['k'] for p in sets[s]]):.2f}, mean words {np.mean([p['n'] for p in sets[s]]):.1f}, "
              f"{(e.step == 0).mean():.0%} at pick 1")
    rng = np.random.default_rng(0)
    print(f"\n  {'booster':30s}" + "".join(f"{s[:24]:>36s}" for s in SETS) + f"{'gap (pooled)':>14s}")
    print(f"  {'':30s}" + f"{'R2 [95% CI]':>22s}{'pick 1':>7s}{'2+':>7s}" * len(SETS))
    for label, path, seq in BOOSTERS:
        b = lgb.Booster(model_file=str(CACHE / path))
        th = SequentialParams.from_dict(json.loads((CACHE / seq).read_text())) if seq else None
        cells, pooled = [], []
        for s in SETS:
            e = ev[s]
            sc = gbt_scores(b, sets[s])
            flat = np.concatenate([sc[i][keep] for i, keep in zip(e.pos_of, e.keep_of)])
            nll, null = e.nll(flat, *e.transform(th, e.drop(sc) if th is not None else None))
            _, bid = np.unique(e.board, return_inverse=True)
            nb = bid.max() + 1
            nb_nll, nb_null = np.bincount(bid, nll), np.bincount(bid, null)
            draws = np.stack([np.bincount(d, minlength=nb) for d in rng.integers(0, nb, (2000, nb))])
            boot = 1 - (draws @ nb_nll) / (draws @ nb_null)
            lo, hi = np.percentile(boot, [2.5, 97.5])
            r2 = lambda m: 1 - nll[m].mean() / null[m].mean()
            first = e.step == 0
            pooled.append(r2(np.ones_like(first)))
            cells.append(f"{pooled[-1]:7.4f} [{lo:.3f}, {hi:.3f}]{r2(first):7.4f}{r2(~first):7.4f}")
        print(f"  {label:30s}" + "".join(f"{c:>36s}" for c in cells) + f"{pooled[1] - pooled[0]:+14.4f}")


if __name__ == "__main__":
    main()
